repos:
  - repo: "https://github.com/domluna/JuliaFormatter.jl"
    rev: "v1.0.33"
    hooks:
      - id: "julia-formatter"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
